### PR TITLE
added 'yb run' command stub

### LINKED ISSUE #102: cli: scaffold the yb run command w/Cobra
good excuse to familiarize myself with Cobra & it's code generation

### PR DESCRIPTION
**Pull request by ksmskm**
closes #102

---
This change is [Reviewable](https://reviewable.io/reviews/yourbase/yourbase/103)

### CODE REVIEW

**Comment by ksmskm** [comment]
I notice my git commit history on this branch includes work on #100 because of the way I setup my branch. I'll avoid that in the future.

**Comment by nictuku** [comment]
It's OK, it will be cleaned up when we rebase it for merging. (It's OK if you don't know how this works yet)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[bazel/bazellib.go, line 29 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jq-oKzZluRo-1GY4T:-L7jq-oKzZluRo-1GY4U:b-x6h0c7) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/bazel/bazellib.go#L29)):*
> strings.TrimSuffix(service, "_deploy.apply")

return strings.TrimSuffix(service, "_deploy.apply")

---

*[bazel/bazellib.go, line 33 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jrX_OO15BaK9PoWnD:-L7jrX_OO15BaK9PoWnE:bseb46m) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/bazel/bazellib.go#L33)):*
> ```Go
> }
> 
> // can take output directly from 'bazel query' cmd
> ```

Format documentation exactly as such:

// CleanTargets takes the raw output of `bazel query` and returns a list of bazel targets.

More here:
https://golang.org/doc/effective_go.html

(I recommend reading this only a bit later)

---

*[bazel/bazellib.go, line 34 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jr6XPK_5MUEAqzqEd:-L7jr6XPK_5MUEAqzqEe:b-zhc2iv) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/bazel/bazellib.go#L34)):*
> ```Go
> 
> // can take output directly from 'bazel query' cmd
> func CleanTargets(targets []byte) []string {
> ```

I believe this package should be a little higher level than this, and this function should be used only internally. We should eventually move the calling function to here (or part of it).

So please add a TODO:

// TODO: Make this an internal function.

---

*[bazel/bazellib.go, line 41 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jqQDPzzTWRv6c4yZq:-L7jqQDPzzTWRv6c4yZr:bd6f92q) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/bazel/bazellib.go#L41)):*
> ```Go
> 	for _, target := range output {
> 		if !strings.Contains(target, ":") {
> 			fmt.Fprintf(os.Stderr, `Malformed target, "%v" lacks ":" character`, target)
> ```

replace "%v" with %q

Also, a more user-friendly message would be to say what format we expect. More about this below.

---

*[bazel/bazellib.go, line 42 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jq4h8wwgSUHwizCFA:-L7jq4h8wwgSUHwizCFB:b-z8uivq) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/bazel/bazellib.go#L42)):*
> ```Go
> 		if !strings.Contains(target, ":") {
> 			fmt.Fprintf(os.Stderr, `Malformed target, "%v" lacks ":" character`, target)
> 			os.Exit(1)
> ```

Don't exit from libraries. This can be called from a server and exiting isn't OK.

Return an error instead. Do this:

return nil, fmt.Errorf(`Expected a bazel target with a format of "//path:target" but the input %q is missing a ":"`, target)

---

*[yb/cmd/deploy.go, line 28 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jrxB6K1PZuLCMwPSa:-L7jrxB6K1PZuLCMwPSb:bwpdozj) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L28)):*
> ```Go
> 		output, err := query.Output()
> 		if err != nil {
> 			fmt.Fprintf(os.Stderr, err.Error())
> ```

return or exit here?

---

*[yb/cmd/deploy.go, line 54 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7js-7ojJp7MSC9ZLkR:-L7js-7ojJp7MSC9ZLkS:bwpdozj) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L54)):*
> ```Go
> 		fmt.Println(string(output))
> 		if err != nil {
> 			fmt.Fprintf(os.Stderr, err.Error())
> ```

return or exit here?

---

*[yb/cmd/run.go, line 1 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jsB7cFSLLmvFfLA9I:-L7jsB7cFSLLmvFfLA9J:b-alxbjh) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/run.go#L1)):*
> ```Go
> // Copyright © 2018 NAME HERE <EMAIL ADDRESS>
> ```

Please remove this entire block of copyright notice, all the way to "package cmd".

It's redundant because the license for our repo is already clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yourbase/yourbase/103#-:-L7jsL40ilCEcIYLN-wi:b-3jutk5)*

**Comment by nictuku** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bazel/bazellib.go, line 33 at r1](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-L7jrX_OO15BaK9PoWnD:-L7l-x8869ZHsrwoqOcw:ba60hhm) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/bazel/bazellib.go#L33)):*
<details><summary><i>Previously, nictuku (Yves Junqueira) wrote…</i></summary><blockquote>

Format documentation exactly as such:

// CleanTargets takes the raw output of `bazel query` and returns a list of bazel targets.

More here:
https://golang.org/doc/effective_go.html

(I recommend reading this only a bit later)
</blockquote></details>

Remove this line now. The entire documentation block must start with `// <FunctionName>`

---

*[yb/cmd/deploy.go, line 28 at r1](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-L7jrxB6K1PZuLCMwPSa:-L7l0KWKC8Tf_AXeJsIY:bbbwobb) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L28)):*
<details><summary><i>Previously, nictuku (Yves Junqueira) wrote…</i></summary><blockquote>

return or exit here?
</blockquote></details>

Sorry, this should really be an exit, with os.Exit(1) because we want the command to return an error code. Same for the other error cases below.

We'll standardize our error logging functions later.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/yourbase/yourbase/103)*

**Comment by nictuku** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/yourbase/yourbase/103#-:-L7l3Ez9BkLsWycJJb-G:bnfp4nl)*

**Comment by ksmskm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[yb/cmd/deploy.go, line 28 at r1](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-L7jrxB6K1PZuLCMwPSa:-L8ADFAgEY2vvySX3cnq:b-4hvi0m) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L28)):*
<details><summary><i>Previously, nictuku (Yves Junqueira) wrote…</i></summary><blockquote>

Sorry, this should really be an exit, with os.Exit(1) because we want the command to return an error code. Same for the other error cases below.

We'll standardize our error logging functions later.
</blockquote></details>

Got it.

---

*[yb/cmd/deploy.go, line 54 at r1](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-L7js-7ojJp7MSC9ZLkR:-L7l4G0r3ScHLxq-RuPL:b-896fix) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L54)):*
<details><summary><i>Previously, nictuku (Yves Junqueira) wrote…</i></summary><blockquote>

return or exit here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/yourbase/yourbase/103)*

**Comment by nictuku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[yb/cmd/deploy.go, line 28 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7jrxB6K1PZuLCMwPSa:-L8ZXr2typTgZvzQnHFj:b2ni2sh) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L28)):*
<details><summary><i>Previously, ksmskm (Kyle Marvich) wrote…</i></summary><blockquote>

Got it.
</blockquote></details>

foo

---

*[yb/cmd/deploy.go, line 54 at r1](https://reviewable.io:443/reviews/yourbase/yourbase/103#-L7js-7ojJp7MSC9ZLkR:-L8ZXv_4vdhkcIXDA0Hq:b2ni2sh) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L54)):*
<details><summary><i>Previously, ksmskm (Kyle Marvich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

foo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yourbase/yourbase/103)*

**Comment by ksmskm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[yb/cmd/deploy.go, line 28 at r1](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-L7jrxB6K1PZuLCMwPSa:-L8ZY2QJ0u88-GuWdeRo:b-896fix) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L28)):*
<details><summary><i>Previously, nictuku (Yves Junqueira) wrote…</i></summary><blockquote>

foo
</blockquote></details>

Done.

---

*[yb/cmd/deploy.go, line 54 at r1](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-L7js-7ojJp7MSC9ZLkR:-L8ZY58z5VwEBs7wPOJ2:b-896fix) ([raw file](https://github.com/yourbase/yourbase/blob/59c6bd6cb9ceef28a14fe1091e22ccde2f99f656/yb/cmd/deploy.go#L54)):*
<details><summary><i>Previously, nictuku (Yves Junqueira) wrote…</i></summary><blockquote>

foo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/yourbase/yourbase/103)*

**Comment by nictuku** [comment]
This needs to be updated to resolve conflicts with master.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/yourbase/yourbase/103#-:-L8Z_0Cq7R4iIvNdtJAG:b-5ug21f)*

**Pull request merged**
